- name: Install httpd on Backend hosts 
  hosts: backend
  gather_facts: false
  become: true
  tasks: 
    - name: Install HTTPD
      ansible.builtin.yum:
        name: httpd
        state: installed
- name: Install NGINX on loadBalancer hosts
  hosts: loadBalancer
  gather_facts: false
  become: true
  tasks:
    - name: Install HTTPD
      ansible.builtin.yum:
        name: nginx
        state: installed

